.github/workflows/changelog.yaml
so the required checks are run on release pr
=> ci: use pat token in release pipeline

commitlint.config.js
=> ci: enable master scope in commit linter

commitlint.config.js
Based on Slack discussion and https://www.notion.so/indykite/Commit-lint-configuration-8ee3971f7c394a9fb60cbe9a2cc1e0b5
=> ci: improve commit lint rules

.github/workflows/release.yml, .pre-commit-config.yaml, go.mod, go.sum, indykite/config_nodes.go, indykite/resource_application_agent_credential.go, indykite/resource_auth_flow.go, indykite/resource_auth_flow_test.go, indykite/resource_authorization_policy.go, indykite/resource_authorization_policy_test.go, indykite/resource_email_notification.go
- Fixing minor bugs
- Updating description to avoid read-only field (https://github.com/hashicorp/terraform-plugin-docs/issues/211)
- Fix Policy config to match Console behaviour 
- Update dependencies
=> Small bug and docs fixes

.github/workflows/tfplugindocs.yaml, .golangci.yml, README.md
Fix for failing `tfplugindocs` GitHub pipeline.
=> ci: fix for failing tfplugindocs workflow

.github/workflows/go-lint.yaml, .golangci.yml
=> style: enable more linter rules

GNUmakefile
Implementing ENG-2398
remove double init
=> fix: terraform init

.github/workflows/go-integration.yaml, README.md
Implementing ENG-2398
- add workflow_dispatch for organization only
=> feat: add workflow_dispatch in integration tests

.github/workflows/build-image-for-jarvis.yaml, docker/ForJarvisProtoLocal.Dockerfile, docker/run_tests_on_local_be.sh
=> test: add image builder for jarvis-proto repo

.github/workflows/go-integration.yaml, tests/provider/test.tf
Implementing ENG-2506
- remove jwk
- remove tests when draft but keep when change status
=> test: remove jwk in test

docker/ForJarvisProtoLocal.Dockerfile, go.mod
=> feat: update version

go.mod, go.sum
=> feat: change go sdk version

examples/resources/indykite_consent/resource.tf, indykite/indykite_suite_test.go, indykite/provider.go, indykite/resource_consent.go, indykite/resource_consent_test.go, tests/provider/test.tf
ENG-1394 implement tda consent configuration support
=> feat: implement tda consent configuration support

docs/resources/ingest_pipeline.md, examples/resources/indykite_consent/resource.tf, indykite/resource_ingest_pipeline.go, indykite/resource_ingest_pipeline_test.go, tests/provider/test.tf
- Marking token as sensitive, so it will not be visible in the console
- Remove returning token as it's a sensitive data
=> fix: ingestion pipeline token

docs/resources/ingest_pipeline.md, indykite/resource_ingest_pipeline.go
Add valid operations to the description of the ingest pipeline operations.
The expected output in the [docs](https://registry.terraform.io/providers/indykite/indykite/latest/docs/resources/ingest_pipeline#operations) should look like that:
=> fix: description of the ingest pipeline operations

go.mod, go.sum, indykite/provider.go, indykite/resource_consent.go, indykite/resource_consent_test.go, indykite/resource_external_data_resolver.go, indykite/resource_external_data_resolver_test.go, indykite/utilities.go
implement ENG-4408
Adds support for ExternalDataResolver
=> feat: add resolver config

.golangci.yml, indykite/resource_consent.go, indykite/resource_external_data_resolver.go
=> fix: update ext data resolver validation

.github/workflows/go-integration.yaml, indykite/provider.go, indykite/resource_entity_matching_pipeline.go, indykite/resource_entity_matching_pipeline_test.go, tests/provider/test.tf
implement ENG-4808
- add entitymatching pipeline config node
=> feat: add entitymatching config node

indykite/resource_entity_matching_pipeline.go, indykite/resource_entity_matching_pipeline_test.go, tests/provider/test.tf
implement ENG-4808
- remove score
=> feat: add location for entitymatching in tf

docs/resources/external_data_resolver.md, indykite/resource_external_data_resolver.go, indykite/resource_external_data_resolver_test.go, tests/provider/test.tf
- Headers are not mandatory part of External data resolver
=> fix: don't require external data headers

CHANGELOG.md, README.md
=> feat: fix release

indykite/resource_application_agent_credential.go
implement ENG-6070
- deprecate public key in credentials
=> chore: deprecate credentials public key

tests/provider/test.tf
implement ENG-4291
- change a test data
=> fix: change a test date

examples/resources/indykite_application_agent_credential/resource.tf, examples/resources/indykite_authorization_policy/resource.tf, examples/resources/indykite_entity_matching_pipeline/resource.tf, examples/resources/indykite_external_data_resolver/resource.tf, examples/resources/indykite_token_introspect/resource.tf, examples/resources/indykite_trust_score_profile/resource.tf, go.mod, go.sum, indykite/provider.go, indykite/resource_authorization_policy_test.go, indykite/resource_consent_test.go, indykite/resource_event_sink.go, indykite/resource_event_sink_test.go, indykite/resource_knowledge_query_test.go, indykite/resource_trust_score_profile.go, terraform.tfstate, tests/provider/test.tf
implement ENG-6067
- add event resource
- update doc
=> feat: add event resource

README.md
=> fix: dummy commit

.github/workflows/release.yml, docs/data-sources/application.md, docs/data-sources/application_agent.md, docs/data-sources/application_agents.md, docs/data-sources/application_space.md, docs/data-sources/application_spaces.md, docs/data-sources/applications.md, docs/data-sources/customer.md, docs/resources/application.md, docs/resources/application_agent.md, docs/resources/application_agent_credential.md, docs/resources/application_space.md, docs/resources/authorization_policy.md, docs/resources/consent.md, docs/resources/entity_matching_pipeline.md, docs/resources/event_sink.md, docs/resources/external_data_resolver.md, docs/resources/ingest_pipeline.md, docs/resources/knowledge_query.md, docs/resources/token_introspect.md, docs/resources/trust_score_profile.md, indykite/resource_trust_score_profile.go, terraform.tfstate
implement ENG-6117
- upd release yaml file dep
- minor modifications in docs
=> feat: minor changes in docs

tests/provider/test.tf
=> test: disable knowledge query until it is ready

tests/provider/test.tf
=> fix: disable tests

tests/provider/test.tf
=> test: bring back knowledge query test

docs/resources/entity_matching_pipeline.md, docs/resources/event_sink.md, docs/resources/token_introspect.md, docs/resources/trust_score_profile.md, examples/resources/indykite_entity_matching_pipeline/resource.tf, examples/resources/indykite_event_sink/resource.tf, examples/resources/indykite_token_introspect/resource.tf, examples/resources/indykite_trust_score_profile/resource.tf, indykite/indykite_suite_test.go, indykite/resource_trust_score_profile.go, indykite/resource_trust_score_profile_test.go, tests/provider/test.tf
implement ENG-6201
- fix float round issue
- change dimensions name to dimension
=> fix: change float management in trust score

tests/provider/test.tf
ENG-6236
Updating CIQ policy test to match the updated strucutre.
=> fix: upadting ciq policy test

.github/workflows/go-lint.yaml, .github/workflows/release.yml, docs/resources/event_sink.md, indykite/resource_event_sink.go, tests/provider/test.tf
implement ENG-6590
- add events sink tests
- update dependencies
- fix doc
=> fix: add tests for eventSink + dep + fix

docker/infra/Dockerfile
[ENG-7272]
[ENG-7272]: https://indykite.atlassian.net/browse/ENG-7272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix docker build for golang:1.24 Debian 13 compatibility

tests/provider/test.tf
implement ENG-7169
- add test for db-connection
=> feat: add dbconnection

indykite/resource_application_space.go
implement ENG-7391
- change timeout according to action
=> fix: fix the time out numbers
